In [1]:
import pandas as pd
import numpy as np

In [2]:
brand = pd.read_csv(r'BRANDINGGoodCopy of ROI Combined - 11-04-2019 (version 1).csv')
data = pd.read_csv(r'allMarketsConsolidatedHere.csv')

In [ ]:
brand.head(1)

In [ ]:
data.head(1)

In [13]:
for j in data['item'].unique():
    for i in range(0,len(brand['SKU'])):
        if brand['SKU'][i] == j:
            data.loc[data['item']==j,"product brand"] = brand['Brand'][i]

In [15]:
listOfUniqueItems3MM = [] 
for i in range(0,len(data['item'])):
    if data['item'][i][0:3] == "3MM": 
        listOfUniqueItems3MM.append(data['item'][i])

In [16]:
for i in listOfUniqueItems3MM:
    data.loc[data['item']==i,"product brand"] = "3M ESPE"

In [17]:
# noProductBrandUnknownItem = 
# data#.loc[data['product brand']== ""]
noProductBrandUnknownItem = data[data.isna().any(axis=1)]
noProductBrandUnknownItem.head()

,vendor,date,order id,country,order city,order state,item,quantity,revenue,total cost,profit,return on sales,product brand
7,amazon,01-01-2019,113-4195757-5332227,USA,RYDAL,PA,MOL-1443-1,1,20.14,16.83,3.31,0.164349553,NaN
10,amazon,01-01-2019,114-5415143-7986625,USA,PEARLAND,TX,MOL-1451,1,20.01,18.00,2.01,0.100449775,NaN
11,amazon,01-01-2019,111-9243091-7060240,USA,JEFFERSON HILLS,PA,MCR-1577,1,44.88,38.02,6.86,0.15285205,NaN
19,amazon,01-01-2019,111-6150993-1034653,USA,GLADWYNE,PA,MOL-1451,1,20.01,18.00,2.01,0.100449775,NaN
20,amazon,01-01-2019,111-0382379-6370613,USA,LEAGUE CITY,TX,MOL-281000,1,14.69,12.06,2.63,0.179033356,NaN

In [18]:
# A list of the unique items
noProductBrandUnknownItem['item'].unique()

array(['MOL-1443-1', 'MOL-1451', 'MCR-1577', 'MOL-281000', 'SOT-154131',
       'MOL-1434', 'SOT-160214', 'CON-187660', 'WEL-52432-U',
       'MOL-281200-1', 'HOLL-14104', 'SOT-166130', 'SOT-140172',
       'SOT-140176', 'SOT-132126', 'MOL-295400', 'CON-187660-1',
       'MOL-295600', 'HOLL-14603(1)', 'MOL-1437-1', 'WEL-52434-U(850)',
       'MOL-281100', 'MOL-295300', 'TOR-MS407W', 'WEL-52434-U(A)',
       'WEL-06190-200', 'WEL-5079135', 'SOT-160172',
       'WEL-52432-U(34 PACK)', 'WEL-24400U', 'SOT-140174',
       'TOR-MS407W(X3)', 'TOR-MS407W(B)', 'TOR-MS407W(C)',
       'WEL-52434-U(102 PACK)', 'MOL-1437(A)', 'WEL-52434-U(X25)',
       'MOL-1434(B)', 'CON-183910E', 'WEL-52432-U(X25)', 'WEL-06000-800',
       'KEL-GEL60GM', 'MOL-281300', 'MOL-1438(B)', 'CON-183910E(X3)',
       'CON-125264E', 'CON-125265E', 'PRK-12-02(A)', 'OMR-HEM-90XL',
       'MOL-281100(B)', 'MOL-1439', 'WEL-92821', 'KEL-GEL15GM',
       'VEC-2410008', 'MDL-MSC094424 (3)', 'MOL-670900(B)',
       'HOL-7910E(B)', 'MDL-MSC094544(B)', 'HOL-7331(E)', 'MOL-1438',
       'HOL-79520(E)', 'CON-420680', 'HOL-7805(E)', 'HOL-7806(E)',
       'CON-420671', 'HOL-7805E(B)', 'HOL-7910(E)', 'PRK-12-02(X2)',
       'MOL-1443', 'HOL-79540(E)', 'BEU-0283-0679-02', 'CON-22771',
       'BEU-0283-0293-31(X2)', 'DER-31815', 'BRO-HBMC-R', 'BRO-HDFB-R',
       'BRO-HSAM-R', 'CON-183910(X3)', 'MOL-295200', 'TOR-MS408W',
       'BRO-HNBO-R', 'BRO-HRLC-R', 'BRO-HGCS-R', 'BEU-0283-0871-31',
       'CON-183910', 'HOL-79530(E)', 'CON-413155', 'MDL-MSC092915H(X3)',
       'S&N-66000040', 'MDL-MSC094308', 'MDL-MSC092625H', 'S&N-66000318',
       'MDL-MSC094604', 'S&N-66000317', 'MDL-MSC094514(X12)',
       'MDL-MSC094853UNSC', 'MOL-1448', 'WEL-01690-410', 'BRO-HIES-R',
       'MDL-MSC094109H(X3)', 'MDL-MSC094544(X3)', 'S&N-66800269',
       'MDL-MSC094420', 'MDL-MSC094424(X3)', 'S&N-66800270',
       'MDL-MSC094604H(X3)', 'MDL-MSC092534(X3)', 'S&N-66250706(B)',
       'S&N-66801068', 'S&N-66800272', 'S&N-66000041', 'S&N-66000319',
       'S&N-66250706', 'MDL-MSC094420(X2)', 'MDL-MSC094424(X2)',
       'LUX-NEO320B', 'LUX-NEO110B', 'LUX-NEO185B', 'LUX-NEO320W',
       'LUX-NEO120B', 'OMR-BP742N', 'PRK-03-08', 'PRK-01-08',
       'MOP-3047_JPA-IP6-BLU', 'LUX-NEO185W', 'LUX-NEO180W',
       'LUX-NEO110W', 'PRK-12-08', 'LUX-NEO250B', 'LUX-NEO120W',
       'PRK-03-08(X2)', 'PRK-12-08(X2)', 'LUX-NEO180B', 'BSN-76168',
       'PRK-01-08(X2)', 'LUX-NEO250W', 'PRK-12-08(X3)', 'OMR-BP710N',
       'OMR-BP652', 'OMR-BP785N', 'CON-187955', 'OMR-BP760N', 'MOL-1437',
       'MDL-MSC092534', 'KER-29835(EU)', 'KRO-KRM302', 'KUR-3303-KA',
       'KUR-3110-KA', 'KUR-3112-KA', 'KUR-3302-KA', 'KUR-3111-KA',
       'DEN-656-2891', 'KUR-3385-KA', 'KUR-3387-KA', 'KUR-2611-KA',
       'KUL-66002193(X6)', 'KUR-2610-KA', 'KUL-66002186E(X6)',
       'KUR-2612-KA', 'KUL-66002103E(X4)', 'KER-29797(EU)', '3MD-7301',
       'BEA-FGSS330(10)', '3MD-7302(X2)', 'COV-8881513843(EU)',
       '3MD-3525TK', 'KER-29951', 'KER-00370(E)', 'KER-31513US(E)',
       'BEA-FGOS702(10)', 'DEN-61C101P', '3MD-3525TKA',
       'KAV-0.411.9680(G)', 'GCD-002258(X2)', 'GCD-002258',
       'CWH-60019803', '3MD-6029A3B-US', 'CWH-250007AA', 'KER-21370(EU)',
       'KER-29899', 'DEN-550294', 'DEN-550774', 'DEN-550773'],
      dtype=object)

In [19]:
# Capturing the first 3 letters of the items and creating a unique list of them
firstLettersItem = []
for i in noProductBrandUnknownItem['item'].unique():
    firstLettersItem.append(i[0:3])
# And then creating a unique list out of them 
firstLettersItem = pd.DataFrame(firstLettersItem)
firstLettersItem = firstLettersItem[0].unique()
firstLettersItem

array(['MOL', 'MCR', 'SOT', 'CON', 'WEL', 'HOL', 'TOR', 'KEL', 'PRK',
       'OMR', 'VEC', 'MDL', 'BEU', 'DER', 'BRO', 'S&N', 'LUX', 'MOP',
       'BSN', 'KER', 'KRO', 'KUR', 'DEN', 'KUL', '3MD', 'BEA', 'COV',
       'KAV', 'GCD', 'CWH'], dtype=object)

In [21]:
missingBrandNameItemList = [
'Molynlycke', 'Microsoft-Xbox', 'Sothys', 'Convatec','Welch Allyn',
'Hollister','Torbot Group','Kelo-cote','Spectra','Omron','Xhekpon','Medline',
'Beutlich','Derma Sciences','Hairfinity','Smith & Nephew','Luxe Bidet Neo',
'Mophie Juice','BSN Medical','KERR','Kromopan','Kuraray','Dentsply',
'Kulzer','3M ESPE','Beaver','Covidien','Kavo','GC','Coltene Whaledent'
]
print(len(missingBrandNameItemList))
print(len(firstLettersItem))
# print(noProductBrandUnknownItem['item'].unique())

30
30

In [22]:
for i in range(0,len(firstLettersItem)):
    for j in noProductBrandUnknownItem['item'].unique():
        if j[0:3] == firstLettersItem[i]:
            data.loc[data["item"]==j,"product brand"] = missingBrandNameItemList[i]

In [23]:
data['product brand'] = data['product brand'].str.upper()

In [29]:
data.to_csv(r'allMarketsConsolidatedHereVersion2.csv')

In [27]:
data

,vendor,date,order id,country,order city,order state,item,quantity,revenue,total cost,profit,return on sales,product brand
0,amazon,01-01-2019,113-6367239-5079454,USA,ST PETERSBURG,FL,3MM-1626W(10),1,6.50,5.37,1.13,0.173846154,3M ESPE
1,amazon,01-01-2019,111-9068523-7753045,USA,Charlotte,NC,3MM-2862(2),1,9.79,8.72,1.07,0.109295199,3M ESPE
2,amazon,01-01-2019,113-0264648-2380248,USA,FREDERICKSBURG,VA,3MM-2862(3),2,21.60,22.06,-0.46,-0.021296296,3M ESPE
3,amazon,01-01-2019,113-9437923-0745861,USA,Winfield,IL,3MM-2113R,1,74.99,64.67,10.32,0.137618349,3M ESPE
4,amazon,01-01-2019,111-9301430-4157819,USA,TORRANCE,CA,3MM-1527-2,1,12.83,10.93,1.90,0.148090413,3M ESPE
5,amazon,01-01-2019,112-6256754-8717046,USA,EVERETT,MA,3MM-1527-2,2,25.58,21.86,3.72,0.145426114,3M ESPE
6,amazon,01-01-2019,114-9064258-3475457,USA,HICKSVILLE,NY,3MM-1626W-25 PACK,1,10.35,3.96,6.39,0.617391304,3M ESPE
7,amazon,01-01-2019,113-4195757-5332227,USA,RYDAL,PA,MOL-1443-1,1,20.14,16.83,3.31,0.164349553,MOLYNLYCKE
8,amazon,01-01-2019,114-8940069-7155464,USA,BOWIE,MD,3MM-1539,2,33.68,27.94,5.74,0.170427553,3M ESPE
9,amazon,01-01-2019,114-3972055-6192239,USA,ODESSA,FL,3MM-2862(3),1,10.80,11.03,-0.23,-0.021296296,3M ESPE
10,amazon,01-01-2019,114-5415143-7986625,USA,PEARLAND,TX,MOL-1451,1,20.01,18.00,2.01,0.100449775,MOLYNLYCKE
11,amazon,01-01-2019,111-9243091-7060240,USA,JEFFERSON HILLS,PA,MCR-1577,1,44.88,38.02,6.86,0.15285205,MICROSOFT-XBOX
12,amazon,01-01-2019,114-5408237-9145812,USA,BLUE POINT,NY,3MM-1626W,1,17.95,15.70,2.25,0.125348189,3M ESPE
13,amazon,01-01-2019,111-3015785-9502623,USA,Columbia,PA,3MM-R1547(50 PACK),1,27.03,20.61,6.42,0.237513873,3M ESPE
14,amazon,01-01-2019,112-6037538-3689846,USA,CARY,NC,3MM-2863(2),3,31.20,27.48,3.72,0.119230769,3M ESPE
15,amazon,01-01-2019,112-5597129-7892210,USA,MIDDLETOWN,NJ,3MM-2560(100),1,13.70,11.29,2.41,0.175912409,3M ESPE
16,amazon,01-01-2019,113-4816505-6819431,USA,WEST NEW YORK,NJ,3MM-1539,1,16.84,13.97,2.87,0.170427553,3M ESPE
17,amazon,01-01-2019,111-2157165-7964213,USA,HOUSTON,TX,MDL-NON80328,1,7.70,7.62,0.08,0.01038961,MEDLINE EMESIS(MISC)
18,amazon,01-01-2019,113-7781583-8136232,USA,CEDAR PARK,TX,3MM-2113R,1,74.99,64.67,10.32,0.137618349,3M ESPE
19,amazon,01-01-2019,111-6150993-1034653,USA,GLADWYNE,PA,MOL-1451,1,20.01,18.00,2.01,0.100449775,MOLYNLYCKE
20,amazon,01-01-2019,111-0382379-6370613,USA,LEAGUE CITY,TX,MOL-281000,1,14.69,12.06,2.63,0.179033356,MOLYNLYCKE
21,amazon,01-01-2019,112-3129064-7647456,USA,Stowe,PA,3MM-2862(2),1,9.79,8.72,1.07,0.109295199,3M ESPE
22,amazon,01-01-2019,113-2547014-8133050,USA,PORTLAND,OR,3MM-2113R,1,74.99,64.67,10.32,0.137618349,3M ESPE
23,amazon,01-01-2019,113-0252234-8853803,USA,TOMBALL,TX,MCR-1577,1,44.88,38.02,6.86,0.15285205,MICROSOFT-XBOX
24,amazon,01-01-2019,112-4453229-0893852,USA,CHESHIRE,CT,3MM-1626W(10),1,6.50,5.37,1.13,0.173846154,3M ESPE
25,amazon,01-01-2019,114-8412690-1441828,USA,GLENDALE,CA,3MM-1527-2,3,38.07,32.73,5.34,0.140267928,3M ESPE
26,amazon,01-01-2019,113-9066253-2874628,USA,MIDDLETOWN,NJ,SOT-154131,1,19.00,17.24,1.76,0.092631579,SOTHYS
27,amazon,01-01-2019,111-0610139-7345004,USA,BROOKLYN,NY,3MM-1626W(10),1,6.50,5.37,1.13,0.173846154,3M ESPE
28,amazon,01-01-2019,113-6218463-4946600,USA,LITCHFIELD,OH,3MM-1527-2,1,12.83,10.93,1.90,0.148090413,3M ESPE
29,amazon,01-01-2019,111-3996287-8975463,USA,CONCORD,CA,3MM-1527-2,1,12.83,10.93,1.90,0.148090413,3M ESPE
...,...,...,...,...,...,...,...,...,...,...,...,...,...
59770,net32,11/04/2019,3770,USA,Hollywood,FL,SDI-8100045,2,69.98,44.62,25.36,0.362389254,SDI
59771,net32,11/04/2019,3766,USA,State College,PA,DEN-66002862,3,250.50,135.93,114.57,0.457365269,DENTSPLY
59772,net32,11/04/2019,3793,USA,Yuba City,CA,SIR-6176510,2,93.00,54.78,38.22,0.410967742,SIRONA
59773,net32,11/04/2019,3770,USA,Hollywood,FL,KUL-66002103(E),2,99.98,77.88,22.10,0.221044209,KULZER
59774,net32,11/04/2019,3815,USA,Durham,NC,SHO-L506,5,62.50,32.60,29.90,0.4784,SHOFU
59775,net32,11/04/2019,3816,USA,Colleyville,TX,3MD-12627(E),8,136.40,85.28,51.12,0.374780059,3M ESPE
59776,net32,11/04/2019,3782,USA,Decatur,GA,KER-25882,2,89.98,64.46,25.52,0.283618582,KERR
59777,net32,11/04/2019,3755,USA,Fayetteville,NC,GCD-000136-B,1,91.25,69.53,21.72,0.238027397,GC
59778,net32,11/04/2019,3794,USA,Irvine,CA,KER-28419,1,31.50,15.74,15.76,0.50031746,KERR
59779,net32,11/04/2019,3810,USA,Cedar Park,TX,TOK-13310(E),2,137.00,83.36,53.64,0.391532847,TOKUYMA
59780,net32,11/04/2019,3780,USA,Glendale,AZ,SIR-6176528,2,82.50,52.24,30.26,0.366787879,SIRONA
59781,net32,11/04/2019,3764,USA,Vacaville,CA,KOD-1753664(E),1,51.50,32.46,19.04,0.369708738,KODAK
59782,net32,11/04/2019,3811,USA,Sacramento,CA,GCD-004714,1,124.70,102.09,22.61,0.181315156,GC
59783,net32,11/04/2019,3757,USA,Rogers,AR,DEN-634352-6,5,750.00,526.45,223.55,0.298066667,DENTSPLY
59784,net32,11/04/2019,3775,USA,Canby,OR,DEN-678776,1,87.99,56.78,31.21,0.354699398,DENTSPLY
59785,net32,11/04/2019,3759,USA,San Francisco,CA,CWH-P-683-0,1,79.99,44.53,35.46,0.443305413,COLTENE WHALEDENT
59786,net32,11/04/2019,3758,USA,Hood River,OR,GCD-004714,1,124.70,102.09,22.61,0.181315156,GC
59787,net32,11/04/2019,3776,USA,Florence,AL,DEN-610007,2,99.00,44.96,54.04,0.545858586,DENTSPLY
59788,net32,11/04/2019,3805,USA,Newton,MA,DEN-678775,3,244.50,145.56,98.94,0.404662577,DENTSPLY
59789,net32,11/04/2019,3812,USA,Nashville,TN,KUL-65872354,1,69.90,50.08,19.82,0.283547926,KULZER
59790,net32,11/04/2019,3787,USA,Los Angeles,CA,KOD-1753664(E),20,1030.00,649.20,380.80,0.369708738,KODAK
59791,net32,11/04/2019,3818,USA,Revere,MA,DEN-634352-6,1,162.50,105.29,57.21,0.352061538,DENTSPLY
59792,net32,11/04/2019,3763,USA,Hackettstown,NJ,NKY-921881,4,42.00,24.16,17.84,0.424761905,KEYSTONE/BOSWORTH
59793,net32,11/04/2019,3773,USA,Richmond,CA,3MD-7510,2,89.40,60.34,29.06,0.325055928,3M ESPE
59794,net32,11/04/2019,3814,USA,Avondale,AZ,3MD-712-036,1,105.00,42.57,62.43,0.594571429,3M ESPE
59795,net32,11/04/2019,3789,USA,Salem,MA,3MD-712-036,1,105.00,42.57,62.43,0.594571429,3M ESPE
59796,net32,11/04/2019,3807,USA,Houston,TX,SHO-1753,1,48.99,29.47,19.52,0.398448663,SHOFU
59797,net32,11/04/2019,3772,USA,Baltimore,MD,KRO-KRM302,10,69.90,38.70,31.20,0.446351931,KROMOPAN
59798,net32,11/04/2019,3801,USA,Matawan,NJ,KUL-65872354,1,69.90,50.08,19.82,0.283547926,KULZER
59799,net32,11/04/2019,4000,USA,Murfreesboro,TN,SUL-21115,1,123.40,51.82,71.58,0.58006483,SULTAN

# Item description

In [2]:
import pandas as pd
import numpy as np

In [2]:
data = pd.read_csv(r'allMarketsConsolidatedHereVersion2.csv')
canDesc = pd.read_csv(r'CANADA2019Jan1-2019Nov4CustomTransaction.csv')
usDesc = pd.read_csv(r'USA2019Jan1-2019Nov4CustomTransaction (2).csv')
netDesc = pd.read_csv(r'itemDescription.csv')

In [3]:
data['item description'] = ''

In [4]:
# adding the extra M for canDesc and US
# Inserting an extra 'M' into all skus which have the first 3 characters '3M-...'

canDesc['sku'] =canDesc['sku'].astype(str)
usDesc['sku'] =usDesc['sku'].astype(str)

for i in range(0,len(canDesc['sku'])):
    if canDesc['sku'][i][0:3] == '3M-':
        canDesc['sku'][i] = canDesc['sku'][i][0:2]+'M'+canDesc['sku'][i][2:len(canDesc['sku'][i])]

for i in range(0,len(usDesc['sku'])):
    if usDesc['sku'][i][0:3] == '3M-':
        usDesc['sku'][i] = usDesc['sku'][i][0:2]+'M'+usDesc['sku'][i][2:len(usDesc['sku'][i])]

C:\Users\carlo\Anaconda3\lib\site-packages\ipykernel_launcher.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  if __name__ == '__main__':
C:\Users\carlo\Anaconda3\lib\site-packages\ipykernel_launcher.py:13: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  del sys.path[0]

In [5]:
canDesc = canDesc.iloc[:,[5,6]]
usDesc = usDesc.iloc[:,[4,5]]
netDesc['SKU'] = netDesc['SKU'].str.upper()

In [6]:
canDesc['sku'] = canDesc['sku'].str.upper()
usDesc['sku'] = usDesc['sku'].str.upper()

In [7]:
# azn Can description
canDescUnique = canDesc.groupby('sku').first()
canDescUnique = canDescUnique.reset_index()
canDescUnique.head()

                 sku                                        description
0       0R-SOE1-ZLU7  FBA Inventory Reimbursement - Customer Service...
1      3MM-1527-1(6)  3M Transpore Surgical Tape 1" x 10 yard (Pack ...
2      3MM-1527-1(B)  3M Transpore Surgical Tape 1" x 10 yard (Pack ...
3      3MM-1527-1-12  3M Transpore Surgical Tape 1" x 10 yard (Pack ...
4  3MM-1527-1-12 (2)              3M 1527-1 Transpore Tape (Pack of 12)

In [8]:
# azn US description
usDescUnique = usDesc.groupby('sku').first()
usDescUnique = usDescUnique.reset_index()
usDescUnique.head()

             sku                                        description
0           1438  Molnlycke 1438 Tubigrip Multipurpose Tubular B...
1  3MM-1527-1-12             3M Transpore Tape 1" x 10 yd Box of 12
2     3MM-1527-2    3M Transpore Surgical Tape, 2" x 10 yds 6 Count
3       3MM-1537  Nexcare Opticlude Orthoptic Eye Patches, Junio...
4   3MM-1537(X4)  Nexcare Opticlude Orthoptic Eye Patches, Junio...

In [9]:
netDesc.head()

              SKU                                        Description
0  3MD-10771(E) 2  3M ESPEIMPRINT 4 LIGHT BODY REFILL CARTRIDGES ...
1      3MD-10771J  3M ESPE IMPRINT 3 HEAVY BODY CARTRIDGE JUMBO P...
2    3MD-12627(E)    3M ESPE CLINPRO SEALANT SYRINGE REFILL 1 X1.2ML
3      3MD-1942FB  3M ESPE MASKS FLUID RESIST (50/BX)            ...
4      3MD-1942FR      3M Espe Masks Fluid Resist- ROSE (50/Bx)

In [10]:
itemDesclist = []
itemDesclist = pd.DataFrame(itemDesclist)

In [11]:
itemDesclist['item'] = ''
itemDesclist['item description'] = ''

In [12]:
data[data['country']=='Canada'].head()

,vendor,date,order id,country,order city,order state,product brand,item,quantity,revenue,total cost,profit,return on sales,item description
1764,amazon,17-01-2019,113-6617365-1853032,Canada,Toronto,ON,MOLYNLYCKE,MOL-281200-1,1,14.00,23.15,-9.15,-0.653571429,
2691,amazon,29-01-2019,113-7132372-8979429,Canada,Montreal,QC,MOLYNLYCKE,MOL-1443-1,1,19.00,20.82,-1.82,-0.095789474,
2692,amazon,29-01-2019,113-7132372-8979429,Canada,Montreal,QC,MOLYNLYCKE,MOL-1443-1,1,19.00,20.81,-1.81,-0.095263158,
2693,amazon,29-01-2019,113-7132372-8979429,Canada,Montreal,QC,MOLYNLYCKE,MOL-1443-1,1,19.00,20.81,-1.81,-0.095263158,
7493,amazon,04-03-2019,114-9677053-8208229,Canada,Montreal,QC,SOTHYS,SOT-140176,1,32.95,38.64,-5.69,-0.172685888,

In [13]:
#canada loopa
for i in range(0,len(canDescUnique['sku'])):
    data.loc[data['item']== canDescUnique['sku'][i], 'item description'] = canDescUnique['description'][i]
    
for i in range(0,len(usDescUnique['sku'])):
    data.loc[data['item']== usDescUnique['sku'][i], 'item description'] = usDescUnique['description'][i]
    
for i in range(0,len(netDesc['SKU'])):
    data.loc[data['item']== netDesc['SKU'][i], 'item description'] = netDesc['Description'][i]

In [14]:
data[data.isna().any(axis=1)]

,vendor,date,order id,country,order city,order state,product brand,item,quantity,revenue,total cost,profit,return on sales,item description
45595,net32,01/02/2019,12933,USA,Prairieville,LA,KERR,KER-29835(EU),2,71.80,47.96,23.84,0.332033426,NaN
47626,net32,02/08/2019,14682,USA,Plano,TX,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
48204,net32,02/22/2019,15259,USA,Denton,TX,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
48331,net32,02/27/2019,15388,USA,Leander,TX,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
48473,net32,03/01/2019,15517,USA,Palmdale,CA,KERR,KER-29797(EU),4,135.60,101.76,33.84,0.249557522,NaN
48491,net32,03/01/2019,15516,USA,Fresno,CA,KERR,KER-29835(EU),6,189.90,143.88,46.02,0.242338073,NaN
49332,net32,03/22/2019,16297,USA,Jacksonville,FL,KERR,KER-29835(EU),4,127.96,95.92,32.04,0.250390747,NaN
49336,net32,03/22/2019,16299,USA,Livingston,CA,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
49344,net32,03/22/2019,16276,USA,Jackson,TN,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
49390,net32,03/25/2019,16325,USA,Fairfield,CA,KERR,KER-29835(EU),3,100.50,71.94,28.56,0.284179104,NaN
49556,net32,03/28/2019,16489,USA,Englewood,CO,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
50132,net32,04/09/2019,17002,USA,Dallas,TX,KERR,KER-29835(EU),3,100.50,71.94,28.56,0.284179104,NaN
50545,net32,04/18/2019,17412,USA,Encinitas,CA,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
50758,net32,04/24/2019,17596,USA,Wallington,NJ,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
50798,net32,04/24/2019,17624,USA,Milford,OH,KERR,KER-29835(EU),2,70.50,47.96,22.54,0.319716312,NaN
56766,net32,08/20/2019,980,USA,Morristown,TN,KERR,KER-29835(EU),4,133.00,95.92,37.08,0.278796992,NaN

In [15]:
data.loc[data['item']=="KER-29835(EU)",'item description'] = "KERR HERCULITE XRV UNIDOSE ENAMEL A1 20/BX"

In [16]:
data[data.isna().any(axis=1)]

,vendor,date,order id,country,order city,order state,product brand,item,quantity,revenue,total cost,profit,return on sales,item description
48473,net32,03/01/2019,15517,USA,Palmdale,CA,KERR,KER-29797(EU),4,135.6,101.76,33.84,0.249557522,NaN

In [17]:
data.loc[data['item']=="KER-29797(EU)",'item description'] = "KERR HERCULITE XRV SYRINGE ENAMEL A1"

In [18]:
data[data.isna().any(axis=1)]

Empty DataFrame
Columns: [vendor, date, order id, country, order city, order state, product brand, item, quantity, revenue, total cost, profit, return on sales, item description]
Index: []

In [20]:
data.to_csv(r"allMarketsConsolidatedHereVersion3.csv")